10 REM === LOGOTRON : GENERATEUR DE NEOLOGISMES ===
20 RANDOMIZE TIMER
30 REM DECLARATION DES TAILLES : NP = NB DE COUPLES PREFIXE/SENS, NS = NB DE COUPLES SUFFIXE/SENS
40 NP = 101 : NS = 84
50 REM DIMENSIONNEMENT DES TABLEAUX (DOUBLE LONGUEUR : MOT + SENS)
60 DIM P$(NP * 2), S$(NS * 2)
70 REM ====== CHARGEMENT DES PREFIXES ET DE LEURS SENS ======
80 FOR I = 1 TO NP * 2
90    READ P$(I)
100 NEXT I
110 REM ====== CHARGEMENT DES SUFFIXES ET DE LEURS SENS ======
120 FOR I = 1 TO NS * 2
130    READ S$(I)
140 NEXT I
150 REM ====== BOUCLE PRINCIPALE ======
160 HOME
170 PRINT "=== LE LOGOTRON (version BASIC) ==="
180 PRINT "Appuyez sur ENTREE pour generer un mot."
190 PRINT "Tapez Q puis ENTREE pour quitter."
200 PRINT
210 GET R$
220 IF R$ = "Q" OR R$ = "q" THEN END
230 REM TIRAGE ALEATOIRE D'UN COUPLE PREFIXE/SENS
240 I = INT(RND * NP) * 2 + 1
250 REM TIRAGE ALEATOIRE D'UN COUPLE SUFFIXE/SENS
260 J = INT(RND * NS) * 2 + 1
270 REM CONSTRUCTION DU MOT ET DE SA DEFINITION
280 NEO$  = P$(I) + S$(J)
290 SENS$ = S$(J + 1) + " " + P$(I + 1)
300 REM AFFICHAGE DES RESULTATS
310 PRINT "NEOLOGISME : "; NEO$
320 PRINT "SIGNIFICATION : "; SENS$
330 PRINT : PRINT
340 GOTO 210
1000 REM ====== DONNEES DES PREFIXES (MOT, SENS) ======
1010 DATA "CLEPTO","LE VOL","CHRONO","LE TEMPS","EPISTEMO","SCIENCE","LOGO","LE DISCOURS","PAN","TOUT","PATHO","MALADIE"
1020 DATA "HEMI","LA MOITIE","CRYPTO","CACHE","EROTICO","EROTISME","GNOSEO","CONNAISSANCE","ORCHIDO","COUILLE","PARALLELO","PARALLELE"
1030 DATA "SEMIO","SENS","ERGO","TRAVAIL","GERONTO","VIEILLARD","COPRO","EXCREMENT","MYCO","CHAMPIGNON","NECRO","MORT","MESO","MILIEU"
1040 DATA "PODO","PIED","PORNO","PORNO","PROTO","PREMIER","SCATO","EXCREMENT","DOXO","OPINION","PLOUTO","RICHESSE","PHONO","SON"
1050 DATA "INFLATO","GONFLEMENT","PYRO","FEU","RETRO","EN ARRIERE","PSYCHO","AME","LITHO","PIERRE","MACRO","GRAND","CHRYSO","OR"
1060 DATA "PHILO","AMOUR","MICRO","PETIT","TECHNO","TECHNIQUE","BIO","VIE","SPELEO","CAVERNE","TOMO","COUPER","TOPO","LIEU"
1070 DATA "ARCHEO","ANCIEN","VIDEO","VOIR","CEPHALO","TETE","CRYO","FROID","TERATO","MONSTRE","PAPYRO","PAPIER","PHYTO","VEGETAL"
1080 DATA "PHRENO","CERVEAU","LATERO","D'A COTE","MORPHO","DE LA FORME","SIDERO","CIEL","CHROMO","COULEUR","ALLO","AUTRE"
1090 DATA "ANTHROPO","HOMME","ADENO","GLANDE","ANISO","AUTRE","AGRO","CHAMP","ARTHRO","ARTICULATION","ASTRO","CIEL"
1100 DATA "AUTO","DE SOI MEME","BACTERIO","BACTERIE","BIBLIO","LIVRE","BRONCHO","BRONCHE","BUTYRO","BEURRE"
1110 DATA "CACO","MAUVAIS","CERCO","QUEUE","CHROMATO","COULEUR","EMBRYO","EMBRYON","CINEMATO","CINEMA"
1120 DATA "CRIO","DU FROID","DERMO","DE LA PEAU","HELIO","DU SOLEIL","HEMATO","DU SANG","HETERO","AUTRE","HOMEO","SEMBLABLE"
1130 DATA "HYDRO","EAU","METEO","DU CIEL","METRO","MESURE","NEO","NOUVEAU","NEURO","LES NERFS","PALEO","ANCIEN"
1140 DATA "SCHIZO","FENDRE","PHYSIO","LE CORPS","THERMO","CHALEUR","ZOO","ANIMAL","TACHY","VITESSE","ODO","CHEMIN"
1150 DATA "GEO","LA TERRE","NUCLEO","NOYAU","GRAPHO","L'ECRITURE","STEREO","SOLIDE","GENO","RACE","ISO","MEME"
1160 DATA "TELE","LOIN","BRADY","LENT","EPI","AUTOUR DE","NOMO","LOI","LOXO","OBLIQUE","PERI","AUTOUR DE"
1170 DATA "GYRO","ROTATION","ICONO","L'IMAGE"
2000 REM ====== DONNEES DES SUFFIXES (MOT, SENS) ======
2010 DATA "GAME","MARIAGE DE","SE","AFFECTION DE","EDRE","EDIFICE","DYNE","ENERGIE","CERQUE","QUEUE","DROME","ROUTE"
2020 DATA "PHOBE","QUI DETESTE","PATHE","MALADE DE","SCAPHE","VEHICULE","TOPE","LIEU","TRON","MACHINE","N","PARTICULE"
2030 DATA "ME","TUMEUR","METRE","MESURE","NAUTE","QUI NAVIGUE","DRAME","THEATRE","IDE","PRESQUE","COSME","UNIVERS DE"
2040 DATA "SOME","CORPS","SPHERE","SPHERE DE","STASE","ARRET DE","TAPHE","TOMBEAU","TROPE","TENDANCE","MANE","MANIAQUE DE"
2050 DATA "GRADE","MARCHER","GRAMME","MESSAGE","GENE","GENERATEUR","ELASTIQUE","ELASTIQUE","CINESE","MOUVEMENT"
2060 DATA "CRATE","POUVOIR","DYNAMIQUE","DYNAMIQUE","CYTE","CELLULE","PHRENE","CERVEAU","CEPHALE","TETE"
2070 DATA "THERAPEUTE","MEDECIN","PHILOSOPHE","PHILOSOPHE","PITHEQUE","SINGE","DIDACTE","ENSEIGNANT"
2080 DATA "PTERE","AILE","SEXUEL","SEXE","MANCIE","PREDIRE","TROPISME","TENDANCE VERS"
2090 DATA "SAURE","ANCETRE DE","STAT","QUI MAINTIENT","PLANE","AVION A","TROPE","QUI RECHERCHE","ZOAIRE","ANIMAL"
2100 DATA "RRAGIE","ECOULEMENT DE","LITHE","PIERRE","CLASTE","CASSEUR DE","MACHIE","COMBAT","DYNE","MACHINE A"
2110 DATA "DENDRON","ARBRE A","LOGIE","DISCOURS SUR","LOGUE","SPECIALISTE DE","LYSE","DECOMPOSITION","SE","AFFECTION DE"
2120 DATA "ALGIE","DOULEUR","PHYSICIEN","PHYSICIEN DE","PHORE","QUI PORTE","CHRONE","TEMPS","CHRONIQUE","REPETITION DE"
2130 DATA "DACTYLE","DOIGT","DOXE","OPINION","CENTRISME","ETRE CENTRE SUR","GONE","ANGLE","DUC","CONDUIT DE"
2140 DATA "LATRE","QUI ADORE","MNESIE","MEMOIRE","MORPHE","DE LA FORME","PHAGE","QUI MANGE","VORE","QUI DEVORE"
2150 DATA "PATHE","MALADE DE","PATHIE","MALADIE DE","PHOBE","QUI DETESTE","PHOBIE","HORREUR DE","PHILE","QUI AIME"
2160 DATA "PHILIE","AMOUR DE","PHONE","SON","PHONIE","SON","POLE","VILLE","THERME","CHALEUR","GRAPHE","QUI ECRIT"
2170 DATA "GENESE","COMMENCEMENT DE"
