10 ctx = MIRCTX()
20 mod = MIRMOD(ctx, "demo")
30 f = MIRFUNC(mod, "add", 2)
40 a = MIRREG(f)
50 b = MIRREG(f)
60 d = MIREMIT(f, "DADD", a, a, b)
70 d = MIRRET(f, a)
80 d = MIRFINISH(mod)
90 PRINT MIRRUN(f, 2, 3)
