name: AMD64-Linux-OSX-Windows-test

on: [push, workflow_dispatch]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: make test
      if: runner.os != 'Windows'
      run: make test
    - name: cmake test
      if: runner.os == 'Windows'
      run: |
        cmake -A x64 -DBUILD_TESTING=ON
        cmake --build . --config Release
        ctest --verbose --output-on-failure

  basic-modes:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [double, long-double, fixed64, msfp]
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: cmake -S . -B build -DBUILD_TESTING=ON -DBASIC_NUM_MODE=${{ matrix.mode }}
    - name: Build
      run: cmake --build build
    - name: Test
      run: ctest --output-on-failure --test-dir build

